# ==========================================
# CONFIGURACIÓN GENERAL Y DEL SERVIDOR
# ==========================================
spring.application.name=SpartanGymAPI
server.port=8080

# ==========================================
# CONEXIÓN A POSTGRESQL (SPARTAN GYM)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/spartangym_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRÍTICO: Usamos 'none' o 'validate' porque ya creamos las tablas manualmente en SQL.
# Si ponemos 'update', Hibernate podría desconfigurar nuestras llaves UUID.
spring.jpa.hibernate.ddl-auto=none

# Mostrar en consola las consultas SQL que Spring hace por debajo (muy útil para debuggear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN JWT
# ==========================================
jwt.secret=SpartanGymSecretKeyParaDesarrolloEnUAM2026Base64NecesitaSerLarga
jwt.expiration=86400000 
# 86400000 ms = 1 día de duración del token